steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/pendle-v3-common/pendle-registry/redis-shake:$COMMIT_SHA'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/pendle-v3-common/pendle-registry/redis-shake:latest'
      - '.'

  # Push the image with commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/pendle-v3-common/pendle-registry/redis-shake:$COMMIT_SHA'

  # Push the image with latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/pendle-v3-common/pendle-registry/redis-shake:latest'

images:
  - 'asia-southeast1-docker.pkg.dev/pendle-v3-common/pendle-registry/redis-shake:$COMMIT_SHA'
  - 'asia-southeast1-docker.pkg.dev/pendle-v3-common/pendle-registry/redis-shake:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
